// import { Geist, Geist_Mono } from "next/font/google";
import { Noto_Sans_JP } from "next/font/google"; // ★ Noto_Sans_JP をインポート
import "./globals.css";

// ★ Noto Sans JP の設定
const notoSansJP = Noto_Sans_JP({
  weight: ['400', '500', '700'], // 必要なウェイトを指定 (例: normal, medium, bold)
  subsets: ['latin'],      // 日本語の場合は 'latin' を指定
  display: 'swap',             // フォント読み込み中の挙動 (推奨)
  variable: "--font-noto-sans-jp", // CSS変数として利用するための名前
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <html lang="en">
    <html lang="ja" className={`${notoSansJP.variable}`}>
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
